# Generated by Django 5.0.1 on 2024-01-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaPage',
            new_name='DishPage',
        ),
    ]
