# Generated by Django 5.0.1 on 2024-01-07 09:01

import dish.models
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='pizzas',
            field=wagtail.fields.StreamField([('pizza', wagtail.snippets.blocks.SnippetChooserBlock(dish.models.Pizza))], blank=True, use_json_field=True),
        ),
    ]
