# Generated by Django 5.0.1 on 2024-01-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_pizzas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='pizzas',
        ),
    ]
