# Generated by Django 5.0.1 on 2024-01-10 06:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTextMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ItemOfHeader',
            fields=[
                ('linktextmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.linktextmixin')),
                ('type', models.TextField(choices=[('L', 'Link'), ('D', 'Dropdown')], default='L', max_length=1)),
            ],
            options={
                'verbose_name': 'Элемент хеадера',
                'verbose_name_plural': 'Элементы хеадера',
            },
            bases=('menu.linktextmixin', models.Model),
        ),
        migrations.CreateModel(
            name='ItemOfDropDown',
            fields=[
                ('linktextmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.linktextmixin')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('parent_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_down_item', to='menu.itemofheader')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('menu.linktextmixin', models.Model),
        ),
    ]
