# Generated by Django 5.0.1 on 2024-01-08 12:29

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('navbar', wagtail.fields.StreamField([('items', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(min_length=1, required=True)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('dropdown', 'Dropdown')]))]))], default='', use_json_field=True)),
                ('test', models.CharField(default='test text', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
