# Generated by Django 5.0.1 on 2024-01-09 08:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropDownItems',
            fields=[
                ('linktextmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.linktextmixin')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('home', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_down_items', to='menu.menupage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('menu.linktextmixin', models.Model),
        ),
        migrations.DeleteModel(
            name='DropDownItem',
        ),
    ]
