# Generated by Django 5.0.1 on 2024-01-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dropdownitems_delete_dropdownitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DropDownItems',
        ),
    ]
