# Generated by Django 5.0.1 on 2024-01-08 15:47

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_homepage_delete_menupage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar', wagtail.fields.StreamField([('NavItemBlock', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(min_length=1, required=True)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('dropdown', 'Dropdown')]))]))], default='', use_json_field=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='navbar',
        ),
    ]
