# Generated by Django 5.0.1 on 2024-01-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_navitem_remove_homepage_navbar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavItem',
            new_name='Header',
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Хеадер'},
        ),
        migrations.RenameField(
            model_name='header',
            old_name='navbar',
            new_name='nav_item',
        ),
    ]
