# Generated by Django 5.0.1 on 2024-01-09 10:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_delete_dropdownitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='ItemOfHeader',
        ),
        migrations.CreateModel(
            name='ItemOfDropDown',
            fields=[
                ('linktextmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.linktextmixin')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('parent_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_down_item', to='menu.itemofheader')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('menu.linktextmixin', models.Model),
        ),
    ]
