# Generated by Django 5.0.1 on 2024-01-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_header_itemofheader_itemofdropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktextmixin',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
