# Generated by Django 5.0.1 on 2024-01-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_header_page'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='MenuPage',
        ),
    ]
