# Generated by Django 5.0.1 on 2024-01-12 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_delete_basket'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='dish',
        ),
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='DishInBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dish.dish')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='dishes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.dishinbasket'),
        ),
    ]
