# Generated by Django 5.0.1 on 2024-01-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_basket_dish_basket_total_price_dishinbasket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, null=True),
        ),
    ]
